#!/usr/bin/env python3
"""Reasoned AVID FAN share for Total Universe profiles.

2026-08-24 (Jenna, explicit approval "Go with what you recommend"):
TUs carry an AVID FAN metadata row again, properly reasoned per
subject, so avid cuts get the same deterministic TU anchor mandated
for gender/age/geo cuts (avid-and-cut-skin-rules.mdc section 3).
This consciously reverses the 2026-07-20 directive that removed the
rows. The OLD rows were generated by a hash-of-subject-name block in
BG.py ("ULTRA-FAST BRAND AWARENESS") - pure noise, tiers 5-35, not
reproducible; every hash-era row was stripped from S3 on 2026-08-24.
THIS module is the reasoned-era replacement: one Claude call that
reasons the share of the subject's engager universe with avid-level
intensity (4+ measured touchpoints in the trailing 12-month window,
vs 1+ for the Total Universe).

CASUAL FAN does NOT return: by the data model the TU IS the casual
cohort, so a casual row is definitionally redundant. It stays
stripped everywhere (strip_avid_casual_fan_rows).

Public API
----------
    reason_avid_share(subject, brand_category,
                      persona_context=None, genpop_hints=None) -> float
        Messy 4dp percent in [3.0, 55.0]. Never a round number, never
        a shared constant, never a bare clamp landing. On any API
        failure returns a deterministic subject-salted draw from the
        category prior band (loud log).

    reason_avid_share_detail(...) -> (float, str)
        Same value plus the model's one-sentence rationale (empty
        string on fallback). Used by smoke tooling and callers that
        want to log the reasoning.

Smoke CLI (no S3 writes):
    python3 -m migration.avid_share_reasoner "Reba McEntire" "MUSICIAN/BAND"
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Optional, Tuple

# Wide sanity clamp. Applied WITH subject-salted jitter so no subject
# ever lands on the bare boundary (rule #1: no pinning).
CLAMP_LO = 3.0
CLAMP_HI = 55.0

# Category prior bands - GUIDANCE for the prompt and the deterministic
# fail-safe draw, never bands the model is pinned to. Keys match the
# canonical BRAND CATEGORY list (canonical-brand-category.mdc);
# "SERIES - *" variants resolve via the SERIES prefix entry.
_DEFAULT_BAND = (10.0, 26.0)
CATEGORY_PRIOR_BANDS = {
    # Concentrated / identity-driven fandoms
    "MUSICIAN/BAND": (16.0, 34.0),
    "GAMES": (22.0, 40.0),
    "GAME PLAYERS": (22.0, 40.0),
    "GAMES - PLAYERS": (22.0, 40.0),
    "PODCAST": (20.0, 36.0),
    "PODCASTER": (18.0, 34.0),
    "INFLUENCER/CREATOR": (16.0, 32.0),
    "CREATOR/INFLUENCER": (16.0, 32.0),
    "ATHLETE": (18.0, 34.0),
    "POLITICS/ACTIVIST": (15.0, 30.0),
    # Engaged genre / mid fandoms
    "ACTOR": (12.0, 24.0),
    "COMEDIAN": (13.0, 26.0),
    "HOST/PERSONALITY": (11.0, 22.0),
    "EMERGING TALENT": (14.0, 30.0),
    "WRITER/DIRECTOR/AUTHOR/ARTIST": (12.0, 25.0),
    "MOVIE": (12.0, 24.0),
    "SERIES": (14.0, 27.0),          # any SERIES - * variant
    "VERTICAL SHORTS": (12.0, 24.0),
    "MLB": (15.0, 30.0),
    "MILB": (14.0, 28.0),
    "NBA": (15.0, 30.0),
    "NFL": (16.0, 32.0),
    "WNBA": (14.0, 28.0),
    "SPORTS ORGANIZATIONS": (14.0, 28.0),
    "SPORTS ORGANIZATION": (14.0, 28.0),
    # Mainstream mass-reach brands / retailers / platforms - audiences
    # built on habit + transactions, not identity.
    "QSR": (7.0, 16.0),
    "RETAILERS": (7.0, 16.0),
    "CPG": (6.0, 14.0),
    "GROCERY": (6.0, 14.0),
    "BEVERAGE": (6.0, 15.0),
    "APPAREL": (7.0, 16.0),
    "APPAREL/FOOTWEAR": (7.0, 16.0),
    "FOOTWEAR": (8.0, 18.0),
    "ACCESSORIES": (6.0, 15.0),
    "BEAUTY": (8.0, 18.0),
    "AUTOMOBILE": (7.0, 16.0),
    "TELECOM": (5.0, 12.0),
    "BANKS": (5.0, 12.0),
    "DIGITAL BANKING": (6.0, 14.0),
    "CREDIT PROVIDERS": (5.0, 12.0),
    "CREDIT PROVIDER": (5.0, 12.0),
    "TRAVEL": (7.0, 16.0),
    "CASUAL DINING": (7.0, 15.0),
    "AMUSEMENT PARKS": (9.0, 20.0),
    "TOY": (9.0, 20.0),
    "STREAMING/PLATFORM": (9.0, 20.0),
    "STREAMING VIDEO": (9.0, 20.0),
    "STREAMING MUSIC": (9.0, 20.0),
    "APP/PLATFORM": (8.0, 18.0),
    "SOCIAL MEDIA": (9.0, 20.0),
    "BROADCAST/CABLE": (8.0, 18.0),
    "MEDIA": (8.0, 18.0),
    "HEALTHCARE": (5.0, 12.0),
    "TRENDS": (8.0, 18.0),
    "SHOPPING INTENT": (8.0, 18.0),
}

# Anthropic web-search tool descriptors (same pair hybrid_reasoning
# uses). Tried newest-first; a permanent tool-type error short-circuits
# inside claude_messages and we fall through to the next variant.
_WEB_SEARCH_TOOL = {
    "type": "web_search_20260209",
    "name": "web_search",
    "max_uses": 4,
}
_WEB_SEARCH_TOOL_LEGACY = {
    "type": "web_search_20250305",
    "name": "web_search",
    "max_uses": 4,
}

_SYSTEM_PROMPT = """You are an audience measurement analyst for a first-party digital panel.

A subject's Total Universe (TU) is everyone with 1+ measured digital \
touchpoint with the subject in the trailing 12 months (search, social, \
media reads/watches, eCommerce, owned channels). The AVID tier is the \
subset with 4+ measured touchpoints in the same window - the \
high-intensity core who repeatedly seek the subject out unprompted.

Your job: estimate the AVID SHARE - what percent of the subject's TU \
engager universe is avid (4+ touchpoints).

Calibration guidance (priors, NOT bands to pin to - reason from the \
subject's actual fan economics and pick the value the evidence supports):
- Concentrated cult fandoms (K-pop acts, anime franchises, superfan-driven \
artists, collector-driven games): often ~30-40.
- Engaged genre / mid fandoms (mainstream musicians, hit TV series, star \
athletes, big podcasts): often ~15-25.
- Mainstream mass-reach brands, retailers, QSR, platforms (audiences built \
on habit and transactions, not identity): often ~8-18.

Calibrate against public fan-funnel signals you know or can verify: \
Luminate's music fan tiers (~20% superfan / ~37% engaged among a genre's \
listeners), platform subscriber-to-MAU ratios, tour attendance vs monthly \
listener ratios, season-ticket vs single-game splits, rewatch/completion \
rates, loyalty-program concentration, social follower-to-active-engager \
ratios. Weigh recency: a subject mid-tour, mid-season, or mid-release runs \
hotter than a dormant one.

Output STRICT JSON only, no prose outside it:
{"avid_share_pct": <number with 4 decimal places, e.g. 18.7342>, \
"rationale": "<ONE sentence naming the strongest signal you used>"}

The value is a PERCENT between 3 and 55. Never output a round number \
(no X.0, X.5, X.25, no multiples of 5, no trailing-zero decimals). It \
must read like a measured panel share, e.g. 23.6187."""


# ---------------------------------------------------------------------------
# Deterministic helpers (hashlib-based - NEVER Python hash(), which is
# salted per-process and not reproducible)
# ---------------------------------------------------------------------------

def _unit(subject: str, salt: str) -> float:
    """Deterministic [0,1) draw from sha256(subject|salt)."""
    h = hashlib.sha256(f"{subject}|{salt}".encode("utf-8")).hexdigest()
    return int(h[:12], 16) / float(16 ** 12)


def _prior_band(brand_category: Optional[str]) -> Tuple[float, float]:
    cat = (brand_category or "").strip().upper()
    if not cat:
        return _DEFAULT_BAND
    if cat in CATEGORY_PRIOR_BANDS:
        return CATEGORY_PRIOR_BANDS[cat]
    if cat.startswith("SERIES"):
        return CATEGORY_PRIOR_BANDS["SERIES"]
    return _DEFAULT_BAND


def _make_messy_4dp(value: float, subject: str, salt: str = "avid-share") -> float:
    """Force a messy 4dp value: never on a .XX00 boundary (covers
    integers, .5, .25, plain-2dp landings), never a zero 4th decimal.
    Subject-salted so the nudge is deterministic per subject."""
    v = round(float(value), 4)
    scaled = int(round(v * 10000))
    if scaled % 100 == 0:
        # Lands on a 2dp boundary - nudge by a salted offset in
        # (-0.29, +0.29), floored away from ~0 so the nudge always moves.
        u = _unit(subject, salt + "|coarse")
        off = (u - 0.5) * 0.58
        if abs(off) < 0.01:
            off = 0.0173 if off >= 0 else -0.0173
        v = round(v + off, 4)
        scaled = int(round(v * 10000))
    if scaled % 10 == 0:
        # 4th decimal is zero - replace it with a salted digit 1-9.
        d = 1 + int(_unit(subject, salt + "|lastdigit") * 9)
        d = min(d, 9)
        scaled = scaled - (scaled % 10) + d
        v = scaled / 10000.0
    return round(v, 4)


def _finalize(value: float, subject: str) -> float:
    """Clamp to [CLAMP_LO, CLAMP_HI] WITH subject-salted jitter (never a
    bare boundary landing), then messy-fix to 4dp. Reflection guard
    keeps the messy nudge from spilling outside the clamp window;
    reflection preserves messiness (10-d is nonzero when d is)."""
    v = float(value)
    if v < CLAMP_LO:
        v = CLAMP_LO + _unit(subject, "avid-clamp-lo") * 1.7
    elif v > CLAMP_HI:
        v = CLAMP_HI - _unit(subject, "avid-clamp-hi") * 2.3
    v = _make_messy_4dp(v, subject)
    if v < CLAMP_LO:
        v = round(2 * CLAMP_LO - v, 4)
    elif v > CLAMP_HI:
        v = round(2 * CLAMP_HI - v, 4)
    return round(v, 4)


def _fallback_share(subject: str, brand_category: Optional[str]) -> float:
    """Deterministic subject-salted draw from the category prior band.
    Same (subject, category) always yields the same value."""
    lo, hi = _prior_band(brand_category)
    u = _unit(subject, f"avid-share-fallback|{(brand_category or '').strip().upper()}")
    return _finalize(lo + u * (hi - lo), subject)


# ---------------------------------------------------------------------------
# Claude response parsing
# ---------------------------------------------------------------------------

def _parse_response(raw: str) -> Tuple[Optional[float], str]:
    """Extract (avid_share_pct, rationale) from the model's text.
    Returns (None, '') when unparseable."""
    if not raw or not raw.strip():
        return None, ""
    val: Optional[float] = None
    rationale = ""
    # Preferred: a JSON object carrying avid_share_pct.
    m = re.search(r"\{[^{}]*\"avid_share_pct\"[^{}]*\}", raw, re.DOTALL)
    if m:
        try:
            obj = json.loads(m.group(0))
            val = float(obj.get("avid_share_pct"))
            rationale = str(obj.get("rationale") or "").strip()
        except Exception:
            val = None
    if val is None:
        m2 = re.search(r"\"avid_share_pct\"\s*:\s*([0-9]+(?:\.[0-9]+)?)", raw)
        if m2:
            try:
                val = float(m2.group(1))
            except Exception:
                val = None
        m3 = re.search(r"\"rationale\"\s*:\s*\"([^\"]*)\"", raw)
        if m3 and not rationale:
            rationale = m3.group(1).strip()
    if val is None:
        return None, ""
    if not (val == val) or val in (float("inf"), float("-inf")):  # NaN/inf
        return None, ""
    # Occasional model slip: 0.22 meaning 22%. Treat sub-1.0 as a
    # fraction and scale (a genuine sub-1% avid share is below the
    # clamp floor anyway, so this mapping is strictly less wrong).
    if 0.0 < val < 1.0:
        val *= 100.0
    if val <= 0.0 or val >= 100.0:
        return None, ""
    return val, rationale


def _build_user_prompt(subject: str, brand_category: Optional[str],
                       band: Tuple[float, float],
                       persona_context: Optional[str],
                       genpop_hints: Optional[str]) -> str:
    parts = [
        f"SUBJECT: {subject}",
        f"BRAND CATEGORY: {(brand_category or 'UNKNOWN').strip().upper()}",
    ]
    if persona_context:
        pc = str(persona_context).strip()
        if len(pc) > 4000:
            pc = pc[:4000] + " ..."
        parts.append(f"AUDIENCE CONTEXT:\n{pc}")
    if genpop_hints:
        gh = str(genpop_hints).strip()
        if len(gh) > 1500:
            gh = gh[:1500] + " ..."
        parts.append(f"AUDIENCE SIZE HINTS:\n{gh}")
    lo, hi = band
    parts.append(
        f"Category prior guidance for this profile type: roughly "
        f"{lo:.0f}-{hi:.0f}. Guidance only - move in either direction "
        f"when the subject's real fan economics say so, anywhere in 3-55."
    )
    parts.append(
        f"Estimate the avid share of {subject}'s engager universe. "
        f"STRICT JSON only."
    )
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def reason_avid_share_detail(
    subject: str,
    brand_category: Optional[str],
    persona_context: Optional[str] = None,
    genpop_hints: Optional[str] = None,
) -> Tuple[float, str]:
    """Reason the subject's avid share via one Claude call. Returns
    (messy 4dp percent in [3.0, 55.0], one-sentence rationale).
    Rationale is '' when the deterministic fallback fired."""
    subject = (subject or "").strip() or "UNKNOWN SUBJECT"
    band = _prior_band(brand_category)
    user = _build_user_prompt(subject, brand_category, band,
                              persona_context, genpop_hints)

    try:
        try:
            from migration.claude_client import claude_messages
        except ImportError:
            from claude_client import claude_messages  # type: ignore
    except Exception as e:
        print(f"⚠️ [avid-share] claude client unavailable "
              f"({type(e).__name__}: {e}) - DETERMINISTIC FALLBACK for "
              f"{subject!r} from prior band {band}")
        return _fallback_share(subject, brand_category), ""

    raw = ""
    # Newest web-search tool first, legacy second, text-only last.
    # Permanent errors (unknown tool type, auth) return '' immediately
    # inside claude_messages, so this ladder is cheap on failure.
    for tools in ([_WEB_SEARCH_TOOL], [_WEB_SEARCH_TOOL_LEGACY], None):
        try:
            raw = claude_messages(
                system=_SYSTEM_PROMPT,
                user=user,
                max_tokens=1200,
                temperature=0.3,
                tools=tools,
            )
        except Exception as e:
            print(f"⚠️ [avid-share] claude_messages raised "
                  f"({type(e).__name__}: {e}); trying next variant")
            raw = ""
        if raw and raw.strip():
            break

    val, rationale = _parse_response(raw)
    if val is None:
        print(f"⚠️ [avid-share] Claude call failed or unparseable for "
              f"{subject!r} ({(brand_category or 'UNKNOWN')}) - "
              f"DETERMINISTIC FALLBACK from prior band {band}")
        return _fallback_share(subject, brand_category), ""

    out = _finalize(val, subject)
    print(f"[avid-share] {subject}: {out:.4f}% "
          f"(raw={val:.4f}; {rationale[:200] if rationale else 'no rationale'})")
    return out, rationale


def reason_avid_share(
    subject: str,
    brand_category: Optional[str],
    persona_context: Optional[str] = None,
    genpop_hints: Optional[str] = None,
) -> float:
    """Reasoned avid share as a messy 4dp percent in [3.0, 55.0]."""
    val, _ = reason_avid_share_detail(
        subject, brand_category,
        persona_context=persona_context, genpop_hints=genpop_hints)
    return val


if __name__ == "__main__":
    import sys as _sys
    _subj = _sys.argv[1] if len(_sys.argv) > 1 else "Reba McEntire"
    _cat = _sys.argv[2] if len(_sys.argv) > 2 else "MUSICIAN/BAND"
    _v, _r = reason_avid_share_detail(_subj, _cat)
    print(f"\n{_subj} ({_cat}): avid share = {_v:.4f}%")
    print(f"rationale: {_r or '(deterministic fallback)'}")
