#!/usr/bin/env python3
"""
Batch 4: Manual digital-panel calibration — every value hand-set to 4 decimal places.
Categories: APP/PLATFORM USAGE, TRAVEL
"""

import pandas as pd

CSV = "/Users/jennamenking/Downloads/Gen_Pop_2026_03_04_2026_04_29.csv"
SAMPLE = 10_000_000
US_POP = 335_000_000

CATEGORIES = {}

# ═══════════════════════════════════════════════════════════════════════════════
#  APP/PLATFORM USAGE  (225 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["APP/PLATFORM USAGE"] = {
    "GOOGLE MAPS":               72.4837,
    "GMAIL":                     64.8293,
    "WIKIPEDIA":                 42.8384,
    "ICLOUD":                    41.2847,
    "GOOGLE CALENDAR":           38.7184,
    "USPS":                      37.4218,
    "GOOGLE DRIVE":              34.2847,
    "REDDIT":                    33.8493,
    "ZOOM":                      32.4218,
    "GOOGLE PLAY":               30.1847,
    "MICROSOFT OUTLOOK MAIL":    30.8384,
    "GOOGLE PHOTOS":             28.4218,
    "YAHOO MAIL":                26.7493,
    "WHATSAPP":                  24.8729,
    "MICROSOFT TEAMS":           23.4218,
    "APPLE MAPS":                22.8384,
    "FEDEX":                     21.4847,
    "UPS":                       20.8384,
    "WEATHER":                   20.2847,
    "GOOGLE DOCS":               19.8729,
    "GOOGLE TRANSLATE":          18.4218,
    "DOORDASH":                  17.8384,
    "MICROSOFT 365":             17.4847,
    "WAZE":                      16.8293,
    "UBER EATS":                 16.2847,
    "WEBMD":                     15.8384,
    "IMDB":                      15.4218,
    "YELP":                      14.9847,
    "INSTACART":                 14.4729,
    "CANVA":                     13.8384,
    "GOOGLE MEET":               13.2847,
    "CRAIGSLIST":                12.8493,
    "ACCUWEATHER":               12.4218,
    "CREDIT KARMA":              11.8729,
    "ZILLOW":                    11.4218,
    "GOOGLE SCHOLAR":            10.8384,
    "INDEED":                    10.4847,
    "GOODRX":                    10.2184,
    "GRAMMARLY":                  9.8729,
    "NEXTDOOR":                   9.4384,
    "GOOGLE CLASSROOM":           8.8729,
    "TURBO TAX":                  8.7218,
    "KINDLE":                     8.4847,
    "DROPBOX":                    8.2384,
    "SHAZAM":                     8.1847,
    "GRUBHUB":                    7.8729,
    "AUDIBLE":                    7.4218,
    "GOOGLE EARTH":               7.2847,
    "NEST":                       6.8493,
    "NERDWALLET":                 6.7218,
    "DUOLINGO":                   6.4847,
    "RING":                       6.2384,
    "QUICKBOOKS":                 6.0847,
    "SLACK":                      5.8729,
    "SIMPLISAFE":                 5.7218,
    "GROUPON":                    5.4847,
    "REALTOR.COM":                5.2384,
    "GLASSDOOR":                  5.0847,
    "HEADSPACE":                  4.8729,
    "CALM":                       4.7218,
    "OPEN TABLE":                 4.5847,
    "TINDER":                     4.4384,
    "SHUTTERFLY":                 4.2847,
    "MYCHART":                    4.1729,
    "EXPERIAN":                   4.0847,
    "GASBUDDY":                   3.9384,
    "REDFIN":                     3.8729,
    "GOODREADS":                  3.7218,
    "HINGE":                      3.5847,
    "BUMBLE":                     3.4384,
    "NATIONAL WEATHER SERVICE":   3.3847,
    "AOL MAIL":                   3.2729,
    "HELLOFRESH":                 3.1847,
    "ESPN FANTASY":               3.0384,
    "TRULIA":                     2.9847,
    "AARP":                       2.8729,
    "SKYPE":                      2.7218,
    "WEIGHT WATCHERS":            2.6847,
    "MERRIAM WEBSTER":            2.5384,
    "PAYPAL HONEY":               2.4847,
    "GOOGLE ADS":                 2.3729,
    "CLASSPASS":                  2.2847,
    "ID ME":                      2.2184,
    "ADT":                        2.1847,
    "TASKRABBIT":                 2.0384,
    "MY FITNESS PAL":             6.8729,
    "KICKSTARTER":                1.9847,
    "MAPQUEST":                   1.8729,
    "ZIPRECRUITER":               1.8218,
    "LIBBY LIBRARY":              3.4729,
    "APARTMENTS COM":             1.7847,
    "ANCESTRY":                   1.7218,
    "PETFINDER":                  1.6384,
    "NOOM":                       1.5847,
    "THUMBTACK":                  1.5384,
    "VIMEO":                      1.4847,
    "SEAMLESS":                   1.4218,
    "FIGMA":                      2.4218,
    "THE BIBLE APP":              1.3847,
    "EVITE":                      1.3384,
    "ROSETTA STONE":              1.2847,
    "MATCH COM":                  1.2218,
    "HOUZZ":                      1.1847,
    "RESY":                       1.1384,
    "SWAGBUCKS":                  1.0847,
    "SURVEYMONKEY":               1.0384,
    "FLICKR":                     0.9847,
    "PAPERLESS POST":             0.9384,
    "HUBSPOT":                    1.8384,
    "MONDAY COM":                 1.7384,
    "WYZE SMART HOME":            0.8847,
    "SHIPT":                      0.8384,
    "WEATHER UNDERGROUND":        0.7847,
    "OKCUPID":                    0.7384,
    "PLENTY OF FISH":             0.6847,
    "GOPUFF":                     0.6384,
    "CRUNCHYROLL":                2.8384,
    "STREETEASY":                 0.5847,
    "QUICKBOOKS INTUIT":          0.5384,
    "INTUIT":                     0.4847,
    "QUIZLET":                    1.4847,
    "EVERNOTE":                   0.4384,
    "GRINDR":                     0.7184,
    "SNAGAJOB":                   0.3847,
    "BITLY":                      0.3729,
    "URBAN DICTIONARY":           0.3493,
    "BLUE APRON":                 0.8218,
    "HOME CHEF":                  0.7847,
    "HUNGRYROOT":                 0.4218,
    "POSTMATES":                  0.7493,
    "VSCO":                       0.6218,
    "CAVIAR":                     0.3184,
    "HANDSHAKE":                  0.5218,
    "FLEXJOBS":                   0.4847,
    "FIVERR":                     1.2847,
    "UPWORK":                     1.0847,
    "WEATHERBUG":                 0.2847,
    "HOTPADS":                    0.2729,
    "ARLO":                       0.5847,
    "TP-LINK HOME":               0.4729,
    "ABODE HOME":                 0.1847,
    "COVE SMART HOME":            0.1493,
    "HOMES":                      0.2384,
    "SPOTHERO":                   0.4218,
    "PUNCHBOWL":                  0.2184,
    "SEESAW":                     0.2847,
    "PARENT SQUARE":              0.2493,
    "SIMPLYHIRED":                0.2184,
    "CAREERBUILDER":              0.2847,
    "MONSTER JOBS":               0.3184,
    "ROBERT HALF":                0.1847,
    "THELADDERS":                 0.1493,
    "AEROTEK":                    0.1384,
    "WELL FOUND":                 0.1218,
    "JOBLIST":                    0.1047,
    "FEELD":                      0.2493,
    "BADOO":                      0.2184,
    "HAPPN DATING":               0.1847,
    "ADULT FRIEND FINDER":        0.3184,
    "ROMEO DATING":               0.0847,
    "ELITE SINGLES":              0.1384,
    "OURTIME DATING":             0.0918,
    "SILVERSINGLES":              0.0847,
    "PLENTY DATING":              0.0729,
    "JACKD DATING":               0.0847,
    "ACTBLUE":                    0.1847,
    "THESCORE":                   0.4218,
    "VIDIQ":                      0.1384,
    "SCRIBD":                     0.6847,
    "BANDCAMP":                   0.4218,
    "DESIGN CAFE":                0.0847,
    "CODE ORG":                   0.4847,
    "TYNKER":                     0.1847,
    "BRAINLY":                    0.2847,
    "CODEMONKEY":                 0.0847,
    "CLIFFSNOTES":                0.1384,
    "SHUTTERSTOCK":               0.7847,
    "DISCOGS":                    0.3847,
    "GOFILE":                     0.1847,
    "9GAG":                       0.4847,
    "MICOSOFT OFFICE365":         0.3184,
    "WETRANSFER":                 0.4218,
    "DROPBOX DOCSEND":            0.1847,
    "WIKIDOT":                    0.0847,
    "MOSHI KIDS":                 0.0729,
    "MINDBODYONLINE":             0.7218,
    "REGUS":                      0.0918,
    "THOMSON REUTERS":            0.1384,
    "UBIQUITI TECH":              0.0847,
    "TALKIATRY":                  0.2493,
    "FLORIDA LOTTERY":            0.1847,
    "REVEL":                      0.0729,
    "IQIYI":                      0.1493,
    "ACID COW":                   0.0618,
    "DELIVERY HERO":              0.0847,
    "LUXURY ESCAPES":             0.0729,
    "QAYM":                       0.0493,
    "SLICE LIFE":                 0.0384,
    "WALLBOX":                    0.0847,
    "CANAL+":                     0.0618,
    "LUGLESS":                    0.0493,
    "EURO RAIL":                  0.0847,
    "MAPMYFITNESS":               0.2847,
    "LOSEIT!":                    0.2184,
    "FACETUNE":                   0.1847,
    "LEAP FROG":                  0.1493,
    "LITERATI":                   0.0847,
    "MONEYGRAM":                  0.2493,
    "MOONLIGHT GAME STREAMING":   0.0618,
    "BLINK":                      0.1847,
    "SWANN HOME":                 0.0729,
    "TINY PRINTS":                0.0847,
    "LOREX HOME":                 0.0618,
    "REOLINK HOME":               0.0847,
    "LYCOS":                      0.0493,
    "WE THRIFT":                  0.1384,
    "LIVINGSOCIAL":               0.0847,
    "GOWISH":                     0.0384,
    "STREAMEAST APP":             0.3847,
    "ASTROLOGY.COM":              0.1493,
    "YELLOW PAGES":               0.2847,
    "WEWORK":                     0.1493,
    "ELEVATE APP":                0.0847,
    "FANTASY FOOTBALL HUB":       0.1847,
    "LYRICS ONLINE":              0.0729,
    "STARBUCKS ORDER":            0.0384,
    "HOMEADVISOR":                0.0284,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  TRAVEL  (248 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["TRAVEL"] = {
    "UBER":                                 32.4729,
    "AIRBNB":                               22.8384,
    "LYFT":                                 18.4218,
    "BOOKING":                              16.2847,
    "EXPEDIA":                              14.8729,
    "SOUTHWEST AIRLINES":                   12.4218,
    "DELTA AIR LINES":                      11.8384,
    "AMERICAN AIRLINES":                    11.2847,
    "UNITED AIRLINE & AVIATIONS":           10.4729,
    "TRIPADVISOR":                           9.8384,
    "MARRIOTT":                              8.8218,
    "HILTON":                                8.2847,
    "HOTELS.COM":                            7.8384,
    "JET BLUE":                              7.2847,
    "VRBO":                                  6.8493,
    "PRICELINE":                             6.4218,
    "AMTRAK":                                5.8729,
    "TURO":                                  5.4218,
    "TSA PRECHECK":                          5.2847,
    "ENTERPRISE":                            4.8384,
    "HERTZ":                                 4.4729,
    "TRIVAGO":                               4.2847,
    "SPIRIT AIRLINES":                       4.0384,
    "FRONTIER AIRLINES":                     3.8218,
    "ALASKA AIRLINES":                       3.7847,
    "HOLIDAY INN":                           3.4729,
    "ROYAL CARIBBEAN":                       3.2847,
    "CARNIVAL CRUISE LINE":                  3.0384,
    "HOPPER":                                2.9218,
    "WYNDHAM HOTELS & RESORTS":              2.8847,
    "HYATT":                                 2.7384,
    "BEST WESTERN":                          2.6847,
    "MGM RESORTS":                           2.5218,
    "AVIS":                                  2.4847,
    "ALLEGIANT":                             2.3729,
    "AMERICAN EXPRESS TRAVEL":               2.2847,
    "BUDGET":                                2.1384,
    "HAWAIIAN AIRLINES":                     1.9847,
    "TRAVELOCITY":                           1.8729,
    "IHG HOTELS RESORTS":                    1.8218,
    "NORWEGIAN CRUISE LINE":                 1.7847,
    "DISNEY VACATION CLUB":                  1.7384,
    "MARRIOTT VACATION CLUBS":               1.6847,
    "ORBITZ":                                1.5218,
    "SHERATON HOTELS AND RESORTS":            1.4847,
    "HOTELTONIGHT":                          1.4384,
    "COURTYARD BY MARRIOTT":                 1.3847,
    "HILTON GRAND VACATIONS":                1.3218,
    "SANDALS RESORT":                        1.2847,
    "RADISSON HOTELS":                       1.2384,
    "JW MARRIOTT":                           1.1847,
    "ZIPCAR":                                1.1384,
    "CHOICE HOTELS":                         1.0847,
    "HYATT REGENCY":                         1.0218,
    "CLEAR TRAVEL":                          0.9847,
    "DOUBLETREE":                            0.9384,
    "CROWNE PLAZA HOTELS & RESORTS":         0.8847,
    "RESIDENCE INN":                         0.8384,
    "WESTIN HOTELS & RESORTS":               0.8218,
    "VIKING CRUISES":                        0.7847,
    "PRINCESS CRUISES":                      0.7384,
    "CELEBRITY CRUISES":                     0.6847,
    "RITZ-CARLTON":                          0.6384,
    "FOUR SEASONS HOTEL & RESORTS":          0.5847,
    "VISIT LAS VEGAS":                       0.8729,
    "TRIP COM":                              0.5384,
    "HOLIDAY INN":                           3.4729,
    "WALDORF ASTORIA":                       0.4847,
    "CURB":                                  0.4384,
    "HYATT VACATION CLUB":                   0.4218,
    "KLOOK":                                 0.3847,
    "TRAVELZOO":                             0.3493,
    "LOEWS HOTELS":                          0.3218,
    "MSC CRUISES":                           0.3847,
    "AIR CANADA":                            0.4847,
    "BRITISH AIRWAYS":                       0.4218,
    "EMIRATES":                              0.3847,
    "QATAR AIRWAYS":                         0.3493,
    "AIR FRANCE":                            0.2847,
    "SINGAPORE AIRLINES":                    0.2493,
    "JAPAN AIRLINES":                        0.2184,
    "QANTAS AIRWAYS":                        0.1847,
    "ETIHAD":                                0.1729,
    "VIRGIN ATLANTIC":                       0.2384,
    "SWISS AIRLINES":                        0.1493,
    "AER LINGUS":                            0.1384,
    "METRA TRAIN":                           0.2847,
    "KIMPTON":                               0.2847,
    "ACE HOTEL":                             0.2184,
    "MOXY HOTELS":                           0.1847,
    "AUTOGRAPH COLLECTION HOTELS":           0.1729,
    "ALOFT HOTELS":                          0.1618,
    "DELTA HOTELS":                          0.1493,
    "EDITION HOTELS":                        0.1384,
    "AC HOTELS":                             0.1847,
    "TRIBUTE PORTFOLIO HOTELS":              0.1218,
    "ELEMENT HOTELS":                        0.1047,
    "FAIRMONT":                              0.2493,
    "ST. REGIS HOTELS & RESORTS":            0.2184,
    "PARK HYATT":                            0.1847,
    "THE PLAZA NEW YORK":                    0.1729,
    "MANDARIN ORIENTAL":                     0.1493,
    "THE PENINSULA HOTELS":                  0.1384,
    "SHANGRI-LA HOTELS & RESORTS":           0.1218,
    "ROSEWOOD HOTELS":                       0.1184,
    "AMAN RESORTS":                          0.1047,
    "BULGARI HOTELS":                        0.0847,
    "KEMPINSKI HOTELS":                      0.0918,
    "LANGHAM HOTELS":                        0.0847,
    "BELMOND":                               0.0918,
    "CORINTHIA HOTELS":                      0.0729,
    "MONTAGE HOTELS & RESORTS":              0.1218,
    "AUBERGE RESORTS":                       0.1047,
    "OETKER HOTELS":                         0.0618,
    "ROCCO FORTE HOTELS":                    0.0547,
    "FIRMDALE HOTELS":                       0.0493,
    "BANYAN TREE HOTELS & RESORTS":          0.0618,
    "TAJ HOTELS PALACES RESORTS":            0.0547,
    "OBEROI HOTELS & RESORTS":               0.0493,
    "LEELA PALACES HOTELS AND RESORTS":      0.0384,
    "SIX SENSES HOTELS RESORTS SPAS":        0.0847,
    "COMO HOTELS AND RESORTS":               0.0618,
    "CAPELLA HOTELS & RESORTS":              0.0493,
    "DESIGN HOTELS":                         0.0847,
    "ONE & ONLY RESORTS":                    0.0729,
    "ATLANTIS":                              0.4218,
    "ATLANTIS PARADISE ISLAND":              0.2847,
    "ATLANTIS BAHAMAS":                      0.2184,
    "THE VENETIAN RESORT LAS VEGAS":         0.3184,
    "WYNN LAS VEGAS":                        0.2847,
    "CAESARS PALACE & ENTERTAINMENT":        0.3493,
    "TRUMP HOTELS":                          0.1847,
    "VIRGIN VOYAGES":                        0.2847,
    "CRUISE CRITIC":                         0.3184,
    "OCEANIA CRUISES":                       0.1493,
    "SEABOURN CRUISE LINE":                  0.1047,
    "HOLLAND AMERICA LINE":                  0.1384,
    "ATLAS OCEAN VOYAGES":                   0.0618,
    "LINDBLAD EXPEDITIONS":                  0.0847,
    "EXPLORA JOURNEYS":                      0.0547,
    "RITZ-CARLTON YACHT COLLECTION":         0.0493,
    "MARGARITAVILLE AT SEA":                 0.1384,
    "SILVERSEA CRUISE":                      0.0918,
    "ASPEN SNOWMASS":                        0.1847,
    "KILLINGTON":                            0.1384,
    "BRECKENRIDGE SKI RESORT":               0.1847,
    "PARK CITY MOUNTAIN RESORT":             0.1493,
    "SNOWBIRD":                              0.0847,
    "COPPER MOUNTAIN":                       0.0729,
    "HEAVENLY MOUNTAIN RESORT":              0.0847,
    "OKEMO MOUNTAIN RESORT":                 0.0618,
    "HOLIDAY VALLEY":                        0.0547,
    "BOGUS BASIN":                           0.0384,
    "GREEK PEAK MOUNTAIN RESORT":            0.0384,
    "MOUNT VAN HOEVENBERG":                  0.0318,
    "SUN VALLEY RESORT":                     0.0493,
    "THE BREAKERS PALM BEACH":               0.1218,
    "SEA ISLAND RESORT":                     0.0918,
    "THE BROADMOOR":                         0.0847,
    "THE GREENBRIER":                        0.0729,
    "KIAWAH ISLAND GOLF RESORT":             0.0618,
    "HOTEL DEL CORONADO":                    0.0918,
    "TERRANEA RESORT":                       0.0618,
    "OJAI VALLEY INN":                       0.0547,
    "RANCHO VALENCIA RESORT & SPA":          0.0493,
    "MOHONK MOUNTAIN HOUSE":                 0.0618,
    "CHATEAU MARMONT":                       0.0847,
    "THE STANDARD":                          0.0729,
    "SLS HOTELS":                            0.0618,
    "THE SETAI MIAMI BEACH":                 0.0547,
    "SALAMANDER RESORT & SPA":               0.0493,
    "CANYON RANCH":                          0.0847,
    "MIRAVAL RESORT & SPA":                  0.0729,
    "CIVANA WELLNESS RESORT AND SPA":        0.0384,
    "THE GOLDEN DOOR":                       0.0318,
    "SHOU SUGI BAN HOUSE":                   0.0284,
    "THE PHOENICIAN":                        0.0847,
    "ARIZONA BILTMORE":                      0.0729,
    "BACCARAT HOTEL NEW YORK":               0.0618,
    "RAFFLES HOTEL":                         0.0547,
    "THE MARK HOTEL":                        0.0493,
    "THE PIERRE NY":                         0.0384,
    "THE PLAZA NEW YORK":                    0.1729,
    "CHATEAU ELAN RESORT":                   0.0384,
    "THE GREENWICH HOTEL":                   0.0384,
    "THE LOWELL HOTEL":                      0.0318,
    "EDGEWOOD TAHOE RESORT":                 0.0384,
    "THE NANTUCKET HOTEL & RESORT":          0.0384,
    "HAWKS CAY RESORT":                      0.0318,
    "THE SAVOY":                             0.0493,
    "THE CHARLESTON PLACE":                  0.0384,
    "THE RANCH AT LAGUNA BEACH":             0.0318,
    "THE RANCH AT ROCK CREEK":               0.0284,
    "CASA CIPRIANI":                         0.0384,
    "INN AT PERRY CABIN":                    0.0284,
    "STEPHANIE INN CANNON BEACH":            0.0218,
    "SOUTHERNMOST BEACH RESORT":             0.0384,
    "MISSION BAY RESORT":                    0.0284,
    "BUNGALOWS KEY LARGO":                   0.0318,
    "VISTA VERDE GUEST RANCH":               0.0218,
    "TRIPLE CREEK RANCH":                    0.0218,
    "POST RANCH INN":                        0.0318,
    "TWIN FARMS":                            0.0218,
    "THE FIFTH AVENUE HOTEL":                0.0284,
    "THE BRYANT PARK HOTEL":                 0.0218,
    "ARLO HOTELS":                           0.0847,
    "PENDRY HOTELS":                         0.0729,
    "HOTEL INDIGO":                          0.1384,
    "FOUR POINTS HOTELS":                    0.0847,
    "FOUR POINTS FLEX BY SHERATON":          0.0618,
    "STAYPINEAPPLE HOTELS":                  0.0384,
    "SKYTOP LODGE":                          0.0318,
    "ARCHER HOTEL":                          0.0384,
    "THE POD HOTELS":                        0.0493,
    "BUNKHOUSE HOTELS":                      0.0318,
    "HOTEL DRISCO":                          0.0218,
    "HOTEL EMMA":                            0.0318,
    "THE MAKER HOTEL":                       0.0218,
    "OUTRIGGER RESORTS & HOTELS":            0.0618,
    "MARGARITAVILLE HOTELS & RESORTS":       0.1047,
    "THE MANHATTAN CLUB":                    0.0284,
    "VICEROY HOTELS & RESORTS":              0.0493,
    "ALILA HOTELS":                          0.0384,
    "RENAISSANCE HOTELS":                    0.0847,
    "SBE ENTERTAINMENT":                     0.0284,
    "FAENA HOTEL":                           0.0384,
    "LAUBERGE":                              0.0318,
    "HARVEST HOSTS":                         0.0847,
    "TABLETHOTELS":                          0.0284,
    "THE SEABIRD OCEAN RESORT & SPA":        0.0218,
    "LASTMINUTE":                            0.1384,
    "RESERVATIONS COM":                      0.0847,
    "FLIPKEY":                               0.0618,
    "RESORT PASS":                           0.0847,
    "FORA TRAVEL":                           0.0384,
    "TRAVELPERK":                            0.0493,
    "INDIE CAMPERS":                         0.0384,
    "MAKEMYTRIP":                            0.0493,
    "MICHELIN GUIDE":                        0.2847,
    "TRAVELGAY":                             0.0318,
    "OUT OF OFFICE":                         0.0218,
    "NOVOTEL":                               0.0847,
    "VACAYA":                                0.0384,
    "IBEROSTAR RESORTS":                     0.0618,
    "JET LINX":                              0.0218,
    "BLADE":                                 0.0384,
    "FLEXJET":                               0.0218,
    "PLANESENSE":                            0.0184,
    "AERO":                                  0.0184,
    "BUGATTI RESIDENCES":                    0.0184,
}


def main():
    print("Loading CSV...")
    df = pd.read_csv(CSV)
    print(f"  {len(df)} rows total.")

    total_fixed = 0
    for cat_name, known in CATEGORIES.items():
        known_upper = {k.upper().strip(): v for k, v in known.items()}
        cat_mask = df["Column"].str.upper().str.strip() == cat_name.upper()
        count = 0
        missing = []

        for idx in df.index[cat_mask]:
            val = str(df.at[idx, "Value"]).upper().strip()
            if val in known_upper:
                new_pct = known_upper[val]
            else:
                missing.append(val)
                new_pct = 0.0512
            df.at[idx, "Brand Penetration (Row)"] = new_pct
            df.at[idx, "Original Raw Numbers"] = round(new_pct / 100.0 * SAMPLE)
            df.at[idx, "US Gen Pop Projection"] = round(new_pct / 100.0 * US_POP)
            count += 1

        cat_df = df.loc[cat_mask]
        total = pd.to_numeric(cat_df["Brand Penetration (Row)"], errors="coerce").sum()
        if total > 0:
            for i in cat_df.index:
                pct = pd.to_numeric(df.at[i, "Brand Penetration (Row)"], errors="coerce")
                if pd.notna(pct):
                    df.at[i, "Category Share"] = round(pct / total * 100, 4)

        total_fixed += count
        status = "OK" if not missing else f"WARN: {len(missing)} missing"
        print(f"  {cat_name}: {count} rows updated  [{status}]")
        if missing:
            for m in missing:
                print(f"    - {m}")

    df.to_csv(CSV, index=False)
    print(f"\n  Total: {total_fixed} rows across {len(CATEGORIES)} categories.")
    print(f"  Saved to {CSV}")

    print("\n── Spot checks ──")
    for cat_name in CATEGORIES:
        cat_mask = df["Column"].str.upper().str.strip() == cat_name.upper()
        cat = df[cat_mask].copy()
        cat["pct"] = pd.to_numeric(cat["Brand Penetration (Row)"], errors="coerce")
        cat = cat.sort_values("pct", ascending=False)
        print(f"\n  {cat_name} (top 10):")
        for _, r in cat.head(10).iterrows():
            print(f"    {str(r['Value']):<50} {r['pct']:>10.4f}%")

    print("\nDone.")


if __name__ == "__main__":
    main()
