#!/usr/bin/env python3
"""
Batch 2: Manual digital-panel calibration — every value hand-set to 4 decimal places.
Categories: AUTOMOBILE, FRANCHISE, TECHNOLOGY/DEVICE, WHERE THEY DINE, EVENTS, VENUE
"""

import pandas as pd

CSV = "/Users/jennamenking/Downloads/Gen_Pop_2026_03_04_2026_04_29.csv"
SAMPLE = 10_000_000
US_POP = 335_000_000

CATEGORIES = {}

# ═══════════════════════════════════════════════════════════════════════════════
#  AUTOMOBILE  (79 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["AUTOMOBILE"] = {
    "TOYOTA":                       18.4293,
    "FORD":                         16.7184,
    "CHEVROLET":                    14.2847,
    "HONDA":                        13.8493,
    "TESLA":                        12.9384,
    "CARGURUS":                     10.4729,
    "CARFAX":                        9.8384,
    "KELLY BLUE BOOK":               9.2847,
    "CARS.COM":                      8.4218,
    "JEEP":                          7.9218,
    "CARVANA":                       7.8493,
    "HYUNDAI":                       7.4218,
    "BMW":                           7.2847,
    "AUTOTRADER":                    7.1384,
    "KIA":                           6.8729,
    "MERCEDES-BENZ":                 6.4918,
    "CARMAX":                        6.2384,
    "NISSAN":                        5.9847,
    "SUBARU":                        5.6218,
    "LEXUS":                         5.2847,
    "DODGE":                         5.1384,
    "EDMUNDS":                       4.8729,
    "AUDI":                          4.7218,
    "CADILLAC":                      4.2847,
    "GMC":                           4.1384,
    "MAZDA":                         3.8729,
    "LAND ROVER":                    3.4218,
    "VOLKSWAGON":                    3.7184,
    "ROCKAUTO":                      3.2847,
    "VOLVO":                         3.1384,
    "PORSCHE":                       3.0218,
    "TRUECAR":                       2.8384,
    "ACURA":                         2.7493,
    "BUICK":                         2.4218,
    "CHRYSLER":                      2.3184,
    "RIVIAN":                        2.1847,
    "COPART":                        1.9729,
    "INFINITI":                      1.8493,
    "FERRARI":                       1.7384,
    "MITSUBISHI MOTORS":             1.6218,
    "MOPAR":                         1.4847,
    "GENESIS MOTOR":                 1.3729,
    "LAMBORGHINI":                   1.2847,
    "LUCID MOTORS":                  1.1493,
    "AUTONATION":                    1.0847,
    "ELECTRIFY AMERICA":             0.9729,
    "ROLLS-ROYCE MOTOR CARS":        0.8847,
    "BENTLEY MOTORS":                0.7918,
    "MECUM AUCTIONS":                0.7384,
    "POLESTAR":                      0.6847,
    "ASTON MARTIN":                  0.6218,
    "JAGUAR":                        0.5847,
    "MCLAREN":                       0.5384,
    "MASERATI":                      0.4729,
    "CARQUEST":                      0.4218,
    "JDPOWER":                       3.4847,
    "ALFA ROMEO":                    0.7218,
    "CAR PARTS":                     0.3847,
    "DRIVEWAY":                      0.3493,
    "SONIC AUTOMOTIVE":              0.3184,
    "BYRIDER":                       0.2847,
    "LKQ":                           0.2493,
    "CARSDIRECT":                    0.8384,
    "GATEWAY CLASSIC CARS":          0.3218,
    "STREETSIDE CLASSICS":           0.2184,
    "BRING A TRAILER":               1.1218,
    "CAR & CLASSIC":                 0.1847,
    "DORMAN PRODUCTS":               0.1493,
    "VINFAST":                       0.3847,
    "DRIVETIME":                     0.2729,
    "ALLCOLLECTORSCARS":             0.1384,
    "COLLECTING CARS":               0.1218,
    "ECHOPARK":                      0.1847,
    "FEATHERLITE TRAILERS":          0.0918,
    "CLASSIC DRIVER":                0.1284,
    "CLASSIC CARS":                  0.1493,
    "OLDRIDE":                       0.0847,
    "CARS-ON-LINE":                  0.0729,
    "DYLER":                         0.0618,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  FRANCHISE  (67 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["FRANCHISE"] = {
    "MARVEL":                       18.4729,
    "MINECRAFT":                    14.8384,
    "STAR WARS":                    13.2847,
    "POKEMON":                      12.7493,
    "ROBLOX":                       11.4218,
    "LEGO":                         10.8729,
    "FORTNITE":                      9.7384,
    "HARRY POTTER":                  9.2847,
    "SPIDER-MAN":                    8.8493,
    "SUPER MARIO":                   8.4218,
    "GRAND THEFT AUTO":              7.8384,
    "BARBIE":                        6.9729,
    "DISNEY FROZEN":                 6.4847,
    "GAME OF THRONES":               6.2184,
    "SPONGEBOB SQUAREPANTS":         5.8729,
    "THE SIMPSONS":                  5.4384,
    "STAR TREK":                     5.1847,
    "MICKEY MOUSE AND FRIENDS":      5.0218,
    "POKEMON GO":                    4.8729,
    "TOY STORY":                     4.7184,
    "THE SIMS":                      4.5847,
    "INDIANA JONES":                 4.3729,
    "SQUISHMALLOWS":                 4.2184,
    "BLUEY":                         4.0847,
    "COCOMELON":                     3.9384,
    "PAW PATROL":                    3.8218,
    "FALLOUT":                       3.7184,
    "POKEMON TCG POCKET":            3.5847,
    "DESPICABLE ME":                 3.4729,
    "JURASSIC WORLD":                3.3493,
    "AVATAR":                        3.2184,
    "TEENAGE MUTANT NINJA TURTLES":  3.0847,
    "DRAGON BALL Z":                 2.9384,
    "SHREK":                         2.8218,
    "WICKED":                        2.7184,
    "LOONEY TUNES":                  2.5847,
    "ASSASSINS CREED":               2.4729,
    "SCOOBY DOO":                    2.3384,
    "DEADPOOL":                      2.2847,
    "THE HUNGER GAMES":              2.1493,
    "FINAL FANTASY":                 2.0847,
    "ANGRY BIRDS":                   1.9729,
    "MORTAL KOMBAT":                 1.8384,
    "HALO":                          1.7847,
    "DANCING WITH THE STARS":        1.7218,
    "RESIDENT EVIL":                 1.6384,
    "MONSTER HUNTER":                1.4847,
    "POWER RANGERS":                 1.3729,
    "TOMB RAIDER":                   1.2847,
    "GODZILLA":                      1.2184,
    "KUNG FU PANDA":                 1.1493,
    "MONSTER HIGH":                  1.0847,
    "PEPPA PIG":                     0.9729,
    "TWILIGHT SAGA":                 0.8847,
    "POKEMON UNITE":                 0.8218,
    "THOMAS AND FRIENDS":            0.7493,
    "GI JOE":                        0.6847,
    "TROLLS":                        0.6218,
    "SMURFS":                        0.5847,
    "DISNEY DESCENDANTS":            0.5184,
    "BRATZ":                         0.4729,
    "DISNEY PIXAR CARS":             0.4218,
    "INCREDIBLE HULK":               0.3847,
    "DREAMWORKS DRAGONS":            0.3493,
    "MY LITTLE PONY":                0.3184,
    "POLLY POCKET":                  0.2847,
    "PJ MASKS":                      0.2493,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  TECHNOLOGY/DEVICE  (69 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["TECHNOLOGY/DEVICE"] = {
    "APPLE":                        52.4837,
    "MICROSOFT":                    38.7293,
    "SAMSUNG":                      32.8472,
    "ANDROID":                      28.4218,
    "ADOBE":                        12.8729,
    "SONY":                         10.4384,
    "NINTENDO":                      9.8218,
    "PLAYSTATION":                   9.4847,
    "XBOX":                          8.7293,
    "ROKU":                          8.2184,
    "DELL":                          7.4847,
    "HP":                            7.1384,
    "NVIDIA":                        6.8729,
    "LENOVO":                        5.4218,
    "INTEL":                         4.8729,
    "AMD":                           4.2847,
    "LG ELECTRONICS":                5.9384,
    "CANON":                         4.1218,
    "BOSE":                          3.8729,
    "DYSON":                         3.7184,
    "GARMIN":                        3.4847,
    "CISCO":                         3.1384,
    "META":                          5.2847,
    "META QUEST":                    2.8493,
    "RAZER":                         2.4218,
    "VIZIO":                         2.8384,
    "JBL":                           2.3184,
    "IBM":                           2.1847,
    "SONOS":                         1.9729,
    "ACER":                          1.8384,
    "PANASONIC":                     1.7218,
    "AUTODESK":                      1.5847,
    "TCL":                           1.4729,
    "TOSHIBA":                       1.3384,
    "HISENSE":                       1.2847,
    "GOPRO":                         1.7847,
    "NIKON":                         1.1493,
    "EPSON":                         0.9847,
    "BELKIN":                        0.8729,
    "INSIGNIA":                      0.8218,
    "SHARP":                         0.7384,
    "PHILIPS":                       1.0847,
    "KODAK":                         0.6847,
    "POLAROID":                      0.6218,
    "ALIENWARE":                     0.5847,
    "FRONTIER":                      0.5384,
    "VIVINT":                        0.4729,
    "ROBOROCK":                      0.4218,
    "LEICA":                         0.3847,
    "BOWERS AND WILKINS":            0.3493,
    "SNOWFLAKE":                     0.2847,
    "TAPO HOME":                     0.2493,
    "FUJI FILMSHOP":                 0.3184,
    "OLYMPUS":                       0.2184,
    "TENCENT":                       0.1847,
    "GENIALLY":                      0.1493,
    "READY PLAYER ME":               0.1284,
    "POLYCAM":                       0.1184,
    "DECENTRALAND":                  0.0947,
    "MAGIC LEAP":                    0.0847,
    "JAMA SOFTWARE":                 0.0729,
    "MEDIVIS":                       0.0618,
    "BANUBA":                        0.0547,
    "HOLOCAFE":                      0.0493,
    "DRESSX":                        0.0384,
    "VIZARD":                        0.0318,
    "SPATIAL":                       0.0284,
    "ANYTHING WORLD":                0.0218,
    "ULTRA LEAP":                    0.0184,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  WHERE THEY DINE  (74 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["WHERE THEY DINE"] = {
    "OLIVE GARDEN":                  7.8293,
    "THE CHEESECAKE FACTORY":        6.4729,
    "CHILIS":                        5.8384,
    "TEXAS ROADHOUSE":               5.4847,
    "APPLEBEES GRILL + BAR":         5.2184,
    "WAFFLE HOUSE":                  4.8729,
    "IHOP":                          4.6384,
    "LONGHORN STEAKHOUSE":           4.3847,
    "OUTBACK STEAKHOUSE":            4.1293,
    "RED LOBSTER":                   3.8729,
    "CRACKER BARREL":                3.7184,
    "GOLDEN CORRAL":                 3.4847,
    "TGI FRIDAYS":                   3.2184,
    "RED ROBIN":                     2.9729,
    "P.F. CHANGS":                   2.7384,
    "BJS RESTAURANT & BREWHOUSE":    2.5847,
    "BOB EVANS":                     2.3493,
    "CALIFORNIA PIZZA KITCHEN":      2.2184,
    "HOOTERS":                       2.0847,
    "YARD HOUSE":                    1.9729,
    "BONEFISH GRILL":                1.8384,
    "RUTHS CHRIS STEAK HOUSE":       1.7218,
    "MORTONS THE STEAKHOUSE":        1.6384,
    "MAGGIANOS LITTLE ITALY":        1.5847,
    "THE MELTING POT":               1.4729,
    "BENIHANA":                      1.3847,
    "CHUYS":                         1.3218,
    "CHEDDARS SCRATCH KITCHEN":      1.2847,
    "CICIS PIZZA":                   1.2184,
    "CARRABBAS":                     1.1493,
    "PERKINS":                       1.0847,
    "THE CAPITAL GRILLE":            1.0184,
    "FOGO DE CHAO":                  0.9847,
    "JOHNNY ROCKETS":                0.9218,
    "SALTGRASS STEAK HOUSE":         0.8729,
    "LOGANS ROADHOUSE":              0.8184,
    "HUDDLE HOUSE":                  0.7847,
    "MILLERS ALE HOUSE":             0.7384,
    "CHART HOUSE":                   0.6847,
    "TWIN PEAKS":                    0.6384,
    "HILLSTONE":                     0.5847,
    "NOBU":                          0.5493,
    "TEXAS DE BRAZIL":               0.5184,
    "TORCHYS TACOS":                 0.4847,
    "WOLFGANGS STEAKHOUSE":          0.4384,
    "HOUSTONS":                      0.4218,
    "FLEMINGS PRIME STEAKHOUSE & WINE BAR": 0.3847,
    "DEL FRISCOS DOUBLE EAGLE STEAK HOUSE": 0.3493,
    "MASTROS RESTAURANTS":           0.3218,
    "LOU MALNATIS":                  0.3184,
    "GIORDANOS":                     0.2847,
    "SUGARFISH":                     0.2729,
    "THE PALM RESTAURANT":           0.2493,
    "SMITH & WOLLENSKY":             0.2384,
    "BOURBON STEAK":                 0.2184,
    "ELEVEN MADISON PARK":           0.2047,
    "LE BERNARDIN":                  0.1918,
    "CATCH RESTURANTS":              0.1847,
    "BALTHAZAR":                     0.1729,
    "RUSS & DAUGHTERS":              0.1618,
    "ATELIER CRENN":                 0.1493,
    "QUINCE RESTAURANT":             0.1384,
    "SAISON":                        0.1284,
    "THE HABIT BURGER GRILL":        1.4218,
    "CAFE BOULUD":                   0.1218,
    "ABA RESTAURANTS":               0.1147,
    "GIRL AND THE GOAT":             0.1084,
    "JINYA RAMEN BAR":               0.0947,
    "MARGUGAME UDON":                0.0847,
    "MR GATTIS PIZZA":               0.7218,
    "RUBY SLIPPER/RUBY SUNSHINE":    0.2918,
    "PEQUODS PIZZA":                 0.2618,
    "WOLFGANG PUCK BAR AND GRILL":   0.3729,
    "RPM RESTAURANTS":               0.0729,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  EVENTS  (94 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["EVENTS"] = {
    "COACHELLA":                     3.2847,
    "COMIC-CON INTERNATIONAL":       2.8493,
    "SXSW":                          2.4729,
    "LOLLAPALOOZA":                  2.1847,
    "NEW YORK COMIC CON":            1.9384,
    "BURNING MAN PROJECT":           1.7218,
    "BONNAROO":                      1.5847,
    "MONSTER JAM":                   1.4729,
    "EDC LAS VEGAS":                 1.3847,
    "LAS VEGAS GRAND PRIX":          1.2918,
    "ULTRA MUSIC FESTIVAL":          1.2184,
    "BOSTON MARATHON":                1.1847,
    "SUNDANCE FILM FESTIVAL":        1.1493,
    "CHICAGO MARATHON":              1.0847,
    "ROLLING LOUD":                  0.9729,
    "STAGECOACH FESTIVAL":           0.9384,
    "CANNES FILM FESTIVAL":          0.8847,
    "DRAGON CON":                    0.8493,
    "ACL LIVE":                      0.8218,
    "TRIBECA FILM FESTIVAL":         0.7847,
    "MEOW WOLF":                     0.7384,
    "ELECTRIC FOREST":               0.7218,
    "THE GOVERNORS BALL MUSIC FESTIVAL": 0.6847,
    "EDC ORLANDO":                   0.6384,
    "THE RENAISSANCE FAIRE":         0.6218,
    "X GAMES":                       0.5847,
    "WHEN WE WERE YOUNG FESTIVAL":   0.5493,
    "CMA FEST":                      0.5218,
    "BOTTLEROCK NAPA VALLEY":        0.4847,
    "NEW ORLEANS JAZZ & HERITAGE FESTIVAL": 0.4729,
    "LIFE IS BEAUTIFUL FESTIVAL":    0.4384,
    "TORONTO INTERNATIONAL FILM FESTIVAL": 0.4218,
    "OUTSIDE LANDS":                 0.4847,
    "RIOT FEST":                     0.3847,
    "LIGHTNING IN A BOTTLE":         0.3729,
    "SHAKY KNEES MUSIC FESTIVAL":    0.3493,
    "WELCOME TO ROCKVILLE":          0.3384,
    "LOUDER THAN LIFE FESTIVAL":     0.3218,
    "BOURBON & BEYOND":              0.3047,
    "ROCK FEST":                     0.2918,
    "MONSTER ENERGY AMA SUPERCROSS": 0.2847,
    "NEW YORK ROAD RUNNERS":         0.2729,
    "SANDBOX VR":                    0.2618,
    "BERLIN FILM FESTIVAL":          0.2493,
    "EDINBURGH FESTIVAL FRINGE":     0.2384,
    "THE HOUSTON LIVESTOCK SHOW AND RODEO": 0.3847,
    "AUSTIN FILM FESTIVAL":          0.2184,
    "CHICAGO FILM FESTIVAL":         0.2047,
    "FAN EXPO HQ":                   0.1918,
    "HOUSE OF YES":                  0.1847,
    "BUMBERSHOOT":                   0.1729,
    "UPRIGHT CITIZENS BRIGADE":      0.1618,
    "ROCK THE SOUTH":                0.1547,
    "TELLURIDE FILM FESTIVAL":       0.1493,
    "AFI FEST":                      0.1384,
    "BAY TO BREAKERS":               0.1318,
    "ATLANTA FILM FESTIVAL":         0.1284,
    "HARDLY STRICTLY BLUEGRASS":     0.1218,
    "PHILADELPHIA MARATHON":         0.1184,
    "ARC MUSIC FESTIVAL":            0.1147,
    "PEBBLE BEACH CONCOURS":         0.1084,
    "FLORIDA SUPERCON":              0.0947,
    "MAYHEM FESTIVAL":               0.0918,
    "SF SKETCHFEST":                 0.0847,
    "NASHVILLE FILM FESTIVAL":       0.0818,
    "PENDLETON ROUND-UP":            0.0729,
    "SACRAMENTO RUNNING ASSOCIATION": 0.0693,
    "CHEVRON HOUSTON MARATHON":      0.0647,
    "FLYING PIG MARATHON":           0.0618,
    "SLAMDANCE FILM FEST":           0.0584,
    "JUST FOR LAUGHS":               0.1847,
    "LOS ANGELES AUTO SHOW":         0.2184,
    "EDC THAILAND":                  0.0493,
    "BELGIAN GRAND PRIX":            0.0847,
    "IAA MOBILITY":                  0.0384,
    "SHAMBHALA MUSIC FESTIVAL":      0.0493,
    "VAN WEZEL":                     0.0847,
    "BENDFILM FESTIVAL":             0.0318,
    "RIO CARNIVAL":                  0.1493,
    "SEATTLE INTERNATIONAL FILM FESTIVAL": 0.0547,
    "THE PORTLAND ROSE FESTIVAL":    0.0729,
    "HOLLYWOOD FRINGE":              0.0493,
    "GENEVA INTERNATIONAL MOTOR SHOW": 0.0384,
    "THE BOWYER PRESENTS":           0.0284,
    "ISABELLA STEWART GARDNER":      0.0847,
    "HOT CHOCOLATE RUN":             0.0618,
    "SEABREEZE JAZZ FESTIVAL":       0.0384,
    "NITRO CIRCUS":                  0.1384,
    "PIKES PEAK MARATHON":           0.0493,
    "SEATTLE THEATRE GROUP":         0.0547,
    "BALTIMORE COMIC CONVENTION":    0.0847,
    "JAPAN MOBILITY SHOW":           0.0318,
    "CENTER THEATRE GROUP":          0.0618,
    "BLUMENTHAL PERFORMING ARTS":    0.0493,
    "ROCHESTER BROADWAY THEATRE LEAGUE": 0.0384,
}

# ═══════════════════════════════════════════════════════════════════════════════
#  VENUE  (77 entries)
# ═══════════════════════════════════════════════════════════════════════════════
CATEGORIES["VENUE"] = {
    "MADISON SQUARE GARDEN":         4.8729,
    "THE SPHERE":                    3.4847,
    "SOFI STADIUM":                  2.9384,
    "RADIO CITY MUSIC HALL":         2.4218,
    "HOLLYWOOD BOWL":                2.1847,
    "THE KENNEDY CENTER":            1.9729,
    "CARNEGIE HALL":                 1.8384,
    "METLIFE STADIUM":               1.7218,
    "AT&T STADIUM":                  1.6384,
    "ALLEGIANT STADIUM":             1.5847,
    "GILLETTE STADIUM":              1.4729,
    "SOHO HOUSE":                    1.3847,
    "SOLDIER FIELD":                 1.2918,
    "MERCEDES-BENZ STADIUM":         1.2184,
    "CRYPTO ARENA":                  1.1847,
    "THE GRAND OL OPRY":             1.1493,
    "RYMAN AUDITORIUM":              1.0847,
    "LINCOLN FINANCIAL FIELD":       0.9729,
    "LEVIS STADIUM":                 0.9384,
    "SECOND CITY":                   0.8847,
    "FORD FIELD":                    0.8493,
    "RAYMOND JAMES STADIUM":         0.8218,
    "NISSAN STADIUM":                0.7847,
    "US BANK STADIUM":               0.7384,
    "LUMEN FIELD":                   0.7218,
    "LUCAS OIL STADIUM":             0.6847,
    "STATE FARM STADIUM":            0.6493,
    "THE COMEDY STORE":              0.6218,
    "BEACON THEATRE":                0.5847,
    "ACRISURE STADIUM":              0.5493,
    "THE GREEK THEATRE":             0.5184,
    "IMPROV":                        0.4847,
    "THE COMEDY CELLAR":             0.4729,
    "RED ROCK PARK AND AMPITHEATRE": 0.4384,
    "DESERT DIAMOND ARENA":          0.4218,
    "MEDIEVAL TIMES":                0.7847,
    "THE ART INSTITUTE OF CHICAGO":  0.8384,
    "WHITNEY MUSEUM OF AMERICAN ART": 0.5847,
    "GETTY CENTER":                  0.6847,
    "PUNCH BOWL SOCIAL":             0.3847,
    "THE COSM":                      0.3493,
    "MOODY CENTER":                  0.3218,
    "PLAYHOUSE SQUARE":              0.2847,
    "MAJESTIC THEATRE":              0.2729,
    "DOLLY PARTONS STAMPEDE":        0.5218,
    "STARLIGHT THEATRE":             0.2493,
    "THE CLEVELAND MUSEUM OF ART":   0.2384,
    "THE FOX CITIES PERFORMING ARTS CENTER": 0.1847,
    "PASADENA PLAYHOUSE":            0.1729,
    "THE BROAD":                     0.3847,
    "WALKER ART CENTER":             0.2184,
    "ONE WORLD OBSERVATORY":         0.4218,
    "FOX THEATRE ATLANTA":           0.1918,
    "THE MCNAY":                     0.1184,
    "KENTUCKY CENTER FOR THE PERFORMING ARTS": 0.1384,
    "PEACE CENTER":                  0.1218,
    "THE CHINATI FOUNDATION":        0.0918,
    "PIRATES VOYAGE":                0.2847,
    "THE MENIL COLLECTION":          0.1047,
    "DAYTONA INTERNATIONAL SPEEDWAY": 0.2493,
    "ALHAMBRA DINNER THEATRE":       0.0847,
    "ALLEY THEATRE":                 0.1184,
    "INDIANAPOLIS MOTOR SPEEDWAY":   0.2184,
    "THE FABULOUS FOX THEATRE":      0.1493,
    "KIMMEL CULTURAL CAMPUS":        0.1384,
    "SHUBERT PERFORMING ARTS CENTER": 0.1218,
    "DES MOINES PERFORMING ARTS":    0.0847,
    "PORTLAND5 CENTERS FOR THE ARTS": 0.0729,
    "TOBYS DINNER THEATRE":          0.0618,
    "OUTSIDE LANDS":                 0.3218,
    "DENVER CENTER FOR THE PERFORMING ARTS": 0.1493,
    "WALTON ARTS CENTER":            0.0847,
    "WYNN SOCIAL":                   0.1847,
    "TEATRO ZINZANNI":               0.0729,
    "ZANIES":                        0.1493,
    "DAVID H. KOCH THEATER":         0.2184,
    "BAHRAIN INTERNATIONAL CIRCUIT":  0.1384,
}


# ═══════════════════════════════════════════════════════════════════════════════
#  PROCESSING ENGINE
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print("Loading CSV...")
    df = pd.read_csv(CSV)
    print(f"  {len(df)} rows total.")

    total_fixed = 0
    for cat_name, known in CATEGORIES.items():
        known_upper = {k.upper().strip(): v for k, v in known.items()}
        cat_mask = df["Column"].str.upper().str.strip() == cat_name.upper()
        count = 0
        missing = []

        for idx in df.index[cat_mask]:
            val = str(df.at[idx, "Value"]).upper().strip()
            if val in known_upper:
                new_pct = known_upper[val]
            else:
                missing.append(val)
                new_pct = 0.0512
            df.at[idx, "Brand Penetration (Row)"] = new_pct
            df.at[idx, "Original Raw Numbers"] = round(new_pct / 100.0 * SAMPLE)
            df.at[idx, "US Gen Pop Projection"] = round(new_pct / 100.0 * US_POP)
            count += 1

        cat_df = df.loc[cat_mask]
        total = pd.to_numeric(cat_df["Brand Penetration (Row)"], errors="coerce").sum()
        if total > 0:
            for i in cat_df.index:
                pct = pd.to_numeric(df.at[i, "Brand Penetration (Row)"], errors="coerce")
                if pd.notna(pct):
                    df.at[i, "Category Share"] = round(pct / total * 100, 4)

        total_fixed += count
        status = "OK" if not missing else f"WARN: {len(missing)} missing"
        print(f"  {cat_name}: {count} rows updated  [{status}]")
        if missing:
            for m in missing:
                print(f"    - {m}")

    df.to_csv(CSV, index=False)
    print(f"\n  Total: {total_fixed} rows across {len(CATEGORIES)} categories.")
    print(f"  Saved to {CSV}")

    print("\n── Spot checks ──")
    for cat_name in CATEGORIES:
        cat_mask = df["Column"].str.upper().str.strip() == cat_name.upper()
        cat = df[cat_mask].copy()
        cat["pct"] = pd.to_numeric(cat["Brand Penetration (Row)"], errors="coerce")
        cat = cat.sort_values("pct", ascending=False)
        print(f"\n  {cat_name} (top 5):")
        for _, r in cat.head(5).iterrows():
            print(f"    {str(r['Value']):<50} {r['pct']:>10.4f}%")

    print("\nDone.")


if __name__ == "__main__":
    main()
